# SyncAI Configuration - Fixed to Follow Working LlamaStack Patterns
# Based on successful Level2_simple_agent_with_websearch.ipynb notebook

# LlamaStack connection
llamastack:
  base_url: "http://lss-chai.apps.cluster-7nc6z.7nc6z.sandbox2170.opentlc.com"
  default_model: "meta-llama/Llama-3.1-8B-Instruct"
  timeout: 60
  
# API Keys and External Services
api_keys:
  tavily_search_api_key: ""

# Agent configurations for SyncAI - FIXED VERSION
agents:
  # Single SyncAI Agent with WORKING instructions based on successful notebook
  - name: "sync_search"
    model: "meta-llama/Llama-3.1-8B-Instruct"
    instructions: |
      You are a helpful AI research assistant that specializes in finding current information.
      When asked to search for information, you must use your search tools.
      Use both web search for latest developments and knowledge base for established information when available.
      Provide comprehensive, well-structured responses with clear source attribution.
      Always respond in a professional and helpful tone.
    tools:
      - "builtin::websearch"
      - name: "builtin::rag"
        args:
          vector_db_ids: ["ai_info"]
    sampling_params:
      strategy:
        type: "greedy"
      max_tokens: 4096
    max_infer_iters: 8  # Higher to allow multiple tool calls

  # Admin agent for system management
  - name: "admin"
    model: "meta-llama/Llama-3.1-8B-Instruct"
    instructions: |
      You are an administrative assistant for SyncAI system management.
      Help with system monitoring, configuration management, and operational tasks.
      Provide clear, actionable responses for administrative queries.

# Vector DB configuration
vector_db:
  default_db_id: "ai_info"
  default_chunk_size: 512
  collections:
    ai_info:
      description: "Curated AI and technology information"
      embedding_model: "sentence-transformers/all-MiniLM-L6-v2"
      chunk_size: 512
      overlap: 50
      vector_dimension: 384

# File storage configuration
file_storage:
  upload_dir: "./uploads"
  max_file_size: 10485760
  allowed_extensions: [".txt", ".md", ".yaml", ".yml", ".json", ".py", ".pdf", ".docx", ".csv"]

# Search configuration
search:
  max_focus_areas: 10
  max_query_length: 500
  max_queries_per_persona: 8
  timeout_seconds: 60
  enable_query_enhancement: true
  enable_alternative_queries: true
  enable_persona_optimization: true
  parallel_processing: false

# App configuration
app:
  title: "SyncAI API"
  version: "1.0.0"
  description: "Professional intelligence platform with working web search"
  debug: false
  host: "0.0.0.0"
  port: 8000

# Logging configuration
logging:
  level: "INFO"
  format: "%(asctime)s [%(levelname)s] %(name)s: %(message)s"

# CORS configuration
cors:
  allow_origins: ["*"]
  allow_credentials: true
  allow_methods: ["*"]
  allow_headers: ["*"]